stages:
  - build
  - delpoy

cache:
  key: ${CI_COMMIT_BEF_NAME}
  paths:
    - node_modules/

build:
  stage: build
  only:
    refs:
    - tags

  script:
    - npm install --progress=false --registry=https://mirrors.huaweicloud.com/repository/npm/
    - npm run build
    - ls -al

  artifacts:
    expire_in: 1 week
    paths:
      - dist
  tags:
    - shell
