stages:
  - build

cache:
  key: ${CI_COMMIT_BEF_NAME}
  paths:
    - node_modules/


build:
  stage: build
  only:
    refs:
    - tags

  script:
    - npm set registry https://registry.npm.taobao.org
    - npm install --progress=false
    - npm run build
    - ls -al

  artifacts:
    expire_in: 1 week
    paths:
      - dist
  tags:
    - shell
